# Generated by Django 3.1.6 on 2021-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ad_views', models.IntegerField(blank=True, null=True)),
                ('impression_percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
