# Generated by Django 3.1.6 on 2021-02-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='ad_views',
            new_name='page_visit',
        ),
        migrations.AddField(
            model_name='advert',
            name='parent_page_visit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
