# Generated by Django 3.1.6 on 2021-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert_app', '0002_auto_20210212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='impression_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advert',
            name='page_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advert',
            name='parent_page_visit',
            field=models.IntegerField(default=0),
        ),
    ]
