# Generated by Django 3.1.6 on 2021-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
